name: Build, Test, and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      REGION: africa-south1 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA .

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
            --image gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA \
            --platform managed \
            --region ${{ env.REGION }} \  # Use the environment variable for the region
            --allow-unauthenticated
